# RNN이란 ?
- Recurrent Neural Networks 의 약자로 , 순환신경망이라는 뜻이다.
- 주로 RNN은 연속형 데이터 , 음성 , NLP , 동영상 등의 데이터에서 사용된다.
- 기존 DNN과 RNN 차이점
    - __RNN은 뉴런의 상태를 저장하고 다음스탭에서 입력으로 사용함__으로써 , 긴 시퀀스에 대해서도 예측이 가능하다

![](images/RNN_1.png)
- 모든 뉴런은 이전 층의 모든 뉴런에서 나오는 입력 연결, 그리고 이어지는 층으로 모든 뉴런을 유도하는 출력 , 즉  __입출력 연결을 둘다 갖고있다.__

# SimpleRNN 레이어
$$ h_t = tanh(U_{xt} + Wh_{t-1})) $$
- tanh 를 활성화 함수로 사용하며 , 위는 실수를 입력받아 -1 ~ 1 사이의 출력값을 반환한다 .

In [3]:
import tensorflow as tf

rnn1 = tf.keras.layers.SimpleRNN(units = 1 , activation = 'tanh', return_sequences=True)

- units : SimpleRNN 레이어에 존재하는 뉴런의 수
- return_sequences : 출력으로 시퀀스 전체를 출력할지 여부를 나타내는 옵션
    - 주로 여러개의 RNN 레이어를 쌓을 때 사용

In [10]:
import numpy as np

X = [] #문제
Y = [] #답

for i in range(6):
    # [0,1,2,3], [1,2,3,4] 같은 정수의 시퀀스를 만든다.
    lst = list(range(i , i+4))
    
    #위에서 구한 시퀀스의 숫자들을 각각 10으로 나눈 다음 저장
    
    #SimpleRNN에 각 타임스텝에 하나씩 숫자가 들어가기 때문에 여기서도 하나씩 분리해서 배열에 저장.
    X.append(list(map(lambda c : [c/10] , lst)))

    #정답에 해당하는4,5 등의 정수 또한 앞에서처럼 10으로 나눠서 저장.
    Y.append((i+4)/10)
    
X = np.array(X)
Y = np.array(Y)
for i in range(len(X)):
    print(X[i] , '\n','위 4개 다음에 올 정답 : ' , Y[i] ,'\n')

[[0. ]
 [0.1]
 [0.2]
 [0.3]] 
 위 4개 다음에 올 정답 :  0.4 

[[0.1]
 [0.2]
 [0.3]
 [0.4]] 
 위 4개 다음에 올 정답 :  0.5 

[[0.2]
 [0.3]
 [0.4]
 [0.5]] 
 위 4개 다음에 올 정답 :  0.6 

[[0.3]
 [0.4]
 [0.5]
 [0.6]] 
 위 4개 다음에 올 정답 :  0.7 

[[0.4]
 [0.5]
 [0.6]
 [0.7]] 
 위 4개 다음에 올 정답 :  0.8 

[[0.5]
 [0.6]
 [0.7]
 [0.8]] 
 위 4개 다음에 올 정답 :  0.9 



>- 위와 같이 4개의 연속되는 숫자와 그 다음에 나올 답을 학습시키면 , 어떤 연속된 숫자 주어지면 그 답을 알아낼까?

In [12]:
#학습 모델 생성

model = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units = 10 , return_sequences = False , input_shape = [4,1]),
    tf.keras.layers.Dense(1)  #한개의 답으로 출력
])

model.compile(optimizer = 'adam' , loss ='mse')
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 1)                 11        
Total params: 131
Trainable params: 131
Non-trainable params: 0
_________________________________________________________________


>- 위 과정에서 input_shape = [4,1]인데 , 각각 timesteps , input_dim 을 나타낸다.
>- timesteps : 순환 신경망이 입력에 대해 계산을 반복하는 획수
>- input_dim : 입력 벡터의 크기

##### 학습

In [18]:
model.fit(X, Y , epochs = 100, verbose = 0)

>- epochs : 학습 반복 수
>- verbose : 진행 과정 확인 True: 1 , False : 0

##### 학습 잘 되었나 확인

In [23]:
print(model.predict(np.array([[ [0.6],[0.7],[0.8],[0.9]  ]])))  
# 우리가 원하는 결과 : 1

print(model.predict(np.array([[ [-0.1],[0.0],[0.1],[0.2]  ]])))
# 우리가 원하는 결과 : 0.3

[[0.8679709]]
[[0.17566746]]


>- 위는 우리가 원하는 결과와는 살짝 다르다 . 이것이 SimpleRNN의 한계이다.
>- 더 좋은 성능을 위해서는 LSTM과 GRU 모델을 주로 사용한다.